# Generated by Django 4.0.5 on 2024-02-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', models.ImageField(upload_to='uploads/category/')),
                ('category_name', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.ImageField(upload_to='uploads/course/')),
                ('course_name', models.CharField(default='', max_length=100, null=True)),
                ('course_price', models.IntegerField(default=1)),
                ('course_desc', models.CharField(default='', max_length=100, null=True)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecourse.category')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=100, null=True)),
                ('Last_name', models.CharField(default='', max_length=100, null=True)),
                ('Email', models.CharField(default='', max_length=100, null=True)),
                ('Password', models.CharField(default='', max_length=100, null=True)),
                ('Mobile', models.BigIntegerField(default='1')),
                ('Gender', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('video_disc', models.CharField(default='', max_length=100, null=True)),
                ('is_preview', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('mobile', models.BigIntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecourse.course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecourse.registration')),
            ],
        ),
    ]
